services:
  - type: web
    name: ebel-ai-phi2
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8002514524:AAGXDdl1NDrsRcsuVP4qg2gST2OsyDxXRMs
      - key: MODEL_PATH
        value: phi-2.Q4_K_S.gguf